/*pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'maven-3.8.6'){
                sh 'mvn clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                withMaven(maven: 'maven-3.8.6'){
                                sh 'mvn test'
            }
        }
        }
        stage('Deploy') {
            steps {
                withMaven(maven: 'maven-3.8.6'){
                    sh 'mvn deploy'
                    }
            }
        }
    }
}*/
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/DevaprasadDR/cucumber.git'
                bat './mvnw clean compile'
            }
        }
    }
}
